language: node_js
node_js:
  - "node"
deploy:
  - provider: npm
    on:
      branch: master
      tags: true
    email: "emin@emin.ch"
    api_key: "${NPM_TOKEN}"
    skip_cleanup: true
  - provider: npm
    on:
      branch: master-cli-v2
      tags: true
    email: "emin@emin.ch"
    api_key: "${NPM_TOKEN}"
    skip_cleanup: true
    tag: next